headTriggerCharacters: 'd'

docTriggerCharacters: "'"

head:
- '"""'
- 'FileName:    ${FileName}'
- 'Description: ${Description}'
- 'Author:      ${Git.UserName} ${Git.Email}'
- 'CreateTime:  ${CreateTime}'
- '"""'

class:
  style: numpy

def:
  style: numpy

# class:
# - '"""'
# - '${Description}'
# - ''
# - 'Attributes:'
# - '[ ${name} (${type}): ${Description}]'
# - '"""'

# def:
# - '"""'
# - '${Description}'
# - ''
# - 'Args:'
# - '[${name} (${type}): ${Description}]'
# - ''
# - 'Returns:'
# - '[(${type}): ${Description}]'
# - '"""'
