headTriggerCharacters: 'd'

docTriggerCharacters: "'"

head:
- '"""'
- 'FileName:    ${FileName}'
- 'Description: ${Description}'
- 'Author:      ${Git.UserName} ${Git.Email}'
- 'CreateTime:  ${CreateTime}'
- '"""'

class:
- 'class"""'
- 'class${FileName}\n'
- 'class${Description}\n'
- 'classAuthor: ${Git.UserName} ${Git.Email}'
- 'classCreateTime: ${CreateTime}'
- 'classLastModifier: ${LastModifier}'
- 'classlastModifyTime: ${lastModifyTime}'
- 'class"""'

function:
- 'function"""'
- 'function${FileName}\n'
- 'function${Description}\n'
- 'functionAuthor: ${Git.UserName} ${Git.Email}'
- 'functionCreateTime: ${CreateTime}'
- 'functionLastModifier: ${LastModifier}'
- 'functionlastModifyTime: ${lastModifyTime}'
- 'function"""'
